service: bongocat

package:
  exclude:
    - node_modules/**

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  memorySize: 128

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:Scan
      Resource:
        - arn:aws:dynamodb:us-east-1:357447601437:table/Bongocat

functions:
  bongo:
    handler: handler.bongo
    events:
      - http:
          path: /slap/the/bongo
          method: get
          cors: true
